{
   "status":200,
   "data":{
      "prev_page":null,
      "next_page":null,
      "has_prev":false,
      "has_next":false,
      "total":10,
      "current_page":1,
      "pages":1,
      "results":[
         {
            "name":"VIVO PRE ",
            "config_v2ray":"",
            "server_hostname":"pre.megassh.shop",
            "description":"TODOS DD",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":1,
            "password":"",
            "udp_port":"7300",
            "category_id":"1",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":" [split][lf]TRACE / HTTP/1.0[crlf]Host: vivo.tl[crlf]Upgrade: WebSocketExtensions[crlf]Connection: Upgrade-Insecure-Requests[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_proxy",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"pre.megassh.shop",
            "sort_order":1,
            "id":1,
            "proxy_port":80,
            "category":{
               "name":"VIVO PRE",
               "id":1,
               "status":"ACTIVE",
               "sort_order":1,
               "user_id":1,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO PRE 2",
            "config_v2ray":"",
            "server_hostname":"pre.megassh.shop",
            "description":"todos dd",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":2,
            "password":"",
            "udp_port":"7300",
            "category_id":"1",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"[delay_split][lf]ACL / HTTP/1.1[lf]Host: [rotate= portal.vivo.com.br;portalrecarga.vivo.com.br/recarga/home/;meuplano.tim.com .br;www.vivo.com.br;buzzfeed.com;mobile.adobe.com;1.0.0.5;1.1.1.1;buzzfeed.com;myspace.com;mobile.google.com;1.0.0.5;spotify.com ;pagamentoonline.emis.co.ao;playwaze.com;wazer.com;soundwaze.com;escolas.playwaze.com;www.wazeunlimited.com;bucs.playwaze.com;ftp.chillwaze.com;unpkg.com;c6bank .com.br;helpypro.stoodi.com.br;atendimento.lojadointer.com.br;creatorsupport.deezer.com:80;itsupport.surveymonkey.com;linefriendshelp.zendesk.com;vivo.interflashplusvpnpro.cloud;m2.interflashplusvpnpro .cloud][crlf][crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_proxy",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"pre.megassh.shop",
            "sort_order":1,
            "id":2,
            "proxy_port":80,
            "category":{
               "name":"VIVO PRE",
               "id":1,
               "status":"ACTIVE",
               "sort_order":1,
               "user_id":1,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO PRE 3",
            "config_v2ray":"",
            "server_hostname":"",
            "description":"todos dd",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":3,
            "password":"",
            "udp_port":"7300",
            "category_id":"1",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"[delay_split][lf]GET / HTTP/1.1[lf]Host: vivo.com.br[lf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_proxy",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"pre.megassh.shop",
            "sort_order":3,
            "id":3,
            "proxy_port":80,
            "category":{
               "name":"VIVO PRE",
               "id":1,
               "status":"ACTIVE",
               "sort_order":1,
               "user_id":1,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO PRE 4",
            "config_v2ray":"",
            "server_hostname":"",
            "description":"todos dd",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":4,
            "password":"",
            "udp_port":"7300",
            "category_id":"1",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"[split][lf]ACL / HTTP/1.1[crlf]Host: microsoft.com[crlf]Upgrade: Upgrade[crlf]Connection: Upgrade[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_proxy",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"",
            "sort_order":4,
            "id":4,
            "proxy_port":80,
            "category":{
               "name":"VIVO PRE",
               "id":1,
               "status":"ACTIVE",
               "sort_order":1,
               "user_id":1,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO PRE 5",
            "config_v2ray":"",
            "server_hostname":"",
            "description":"todos dd",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":5,
            "password":"",
            "udp_port":"7300",
            "category_id":"1",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"[delay_split][lf]GET / HTTP/1.1[lf]Host: portal.vivo.com.br\\n\\n\\n \\n",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_proxy",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"br2.betao.xyz",
            "sort_order":5,
            "id":5,
            "proxy_port":80,
            "category":{
               "name":"VIVO PRE",
               "id":1,
               "status":"ACTIVE",
               "sort_order":1,
               "user_id":1,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO EASY 1",
            "config_v2ray":"",
            "server_hostname":"104.18.7.80",
            "description":"promoção easy",
            "username":"",
            "server_port":8080,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":6,
            "password":"",
            "udp_port":"7300",
            "category_id":"2",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"GET / HTTP/1.1[crlf]Host: br2.betao.xyz[crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_direct",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"104.18.7.80",
            "sort_order":1,
            "id":6,
            "proxy_port":8080,
            "category":{
               "name":"VIVO EASY",
               "id":2,
               "status":"ACTIVE",
               "sort_order":2,
               "user_id":2,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO EASY 2",
            "config_v2ray":"",
            "server_hostname":"104.18.6.80",
            "description":"promoção easy",
            "username":"",
            "server_port":8080,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":7,
            "password":"",
            "udp_port":"7300",
            "category_id":"2",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"GET / HTTP/1.1[crlf]Host: br2.betao.xyz[crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_direct",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"104.18.6.80",
            "sort_order":1,
            "id":7,
            "proxy_port":8080,
            "category":{
               "name":"VIVO EASY",
               "id":2,
               "status":"ACTIVE",
               "sort_order":2,
               "user_id":2,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO EASY 3",
            "config_v2ray":"",
            "server_hostname":"104.17.70.206",
            "description":"easy promoção",
            "username":"",
            "server_port":8080,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":8,
            "password":"",
            "udp_port":"7300",
            "category_id":"2",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"GET / HTTP/1.1[crlf]Host: br2.betao.xyz[crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_direct",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"104.17.70.206",
            "sort_order":3,
            "id":8,
            "proxy_port":8080,
            "category":{
               "name":"VIVO EASY",
               "id":2,
               "status":"ACTIVE",
               "sort_order":2,
               "user_id":2,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"Vivo Easy 4",
            "config_v2ray":"",
            "server_hostname":"104.18.7.41",
            "description":"promoção easy",
            "username":"",
            "server_port":8080,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":9,
            "password":"",
            "udp_port":"7300",
            "category_id":"2",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"GET / HTTP/1.1[crlf]Host: br2.betao.xyz[crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_direct",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"104.18.7.41",
            "sort_order":4,
            "id":9,
            "proxy_port":8080,
            "category":{
               "name":"VIVO EASY",
               "id":2,
               "status":"ACTIVE",
               "sort_order":2,
               "user_id":2,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO CONTROLE 1",
            "config_v2ray":"",
            "server_hostname":"104.17.70.206",
            "description":"com plano controle",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/V1ZxzjQ.png",
            "user_id":10,
            "password":"",
            "udp_port":"7300",
            "category_id":"5",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"BASELINE-CONTROL / HTTP/1.1[crlf]Host: pre.megassh.shop[crlf]Upgrade: Websocket[crlf]Connection: Upgrade[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_proxy",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"104.17.70.206",
            "sort_order":5,
            "id":10,
            "proxy_port":80,
            "category":{
               "name":"VIVO CONTROLE",
               "id":5,
               "status":"ACTIVE",
               "sort_order":1,
               "user_id":5,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO CONTROLE  2",
            "config_v2ray":"",
            "server_hostname":"",
            "description":"",
            "username":"",
            "server_port":null,
            "icon_image":"",
            "user_id":11,
            "password":"",
            "udp_port":"",
            "category_id":"5",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssl_proxy",
            "url_check_user":"",
            "config_openvpn":"",
            "proxy_hostname":"",
            "sort_order":2,
            "id":11,
            "proxy_port":null,
            "category":{
               "name":"VIVO CONTROLE",
               "id":5,
               "status":"ACTIVE",
               "sort_order":2,
               "user_id":5,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"VIVO CONTROLE 3",
            "config_v2ray":"",
            "server_hostname":"",
            "description":"",
            "username":"",
            "server_port":null,
            "icon_image":"",
            "user_id":12,
            "password":"",
            "udp_port":"",
            "category_id":"5",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssl_proxy",
            "url_check_user":"",
            "config_openvpn":"",
            "proxy_hostname":"",
            "sort_order":3,
            "id":12,
            "proxy_port":null,
            "category":{
               "name":"VIVO CONTROLE",
               "id":5,
               "status":"ACTIVE",
               "sort_order":3,
               "user_id":5,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"TIM PROXY 1",
            "SSH":"",
            "server_hostname":"104.19.239.25",
            "description":"SALDO VALIDO",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/Z9xX94V.png",
            "user_id":11,
            "password":"",
            "udp_port":"7300",
            "category_id":"3",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"CONNECT / HTTP/1.9[crlf]host: c6bank.com.br[crlf][crlf][split][crlf]OPTIONS- // HTTP/1.9[crlf]host: br2.betao.xyzz[crlf]Expect: 200-continue[crlf]Proxy-Connection: Keep-Alive[crlf]Keep-Alive: timeout=5, max=1000[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf]Sec WebSocketExtensions: superspeed[crlf]Last-Modified: Fri, 17 March 2022 04:32:39 GMT[crlf]Server: Qnax[crlf]User-Agent: Mozilla/5.0 (Linux; Android 4.4.2); Nexus 5 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Mobile Safari/537.36 OPR/20.0.1396.72047[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_direct",
            "url_check_user":"",
            "config_openvpn":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "proxy_hostname":"104.19.239.25",
            "sort_order":1,
            "id":11,
            "proxy_port":80,
            "category":{
               "name":"TIM SALDO VALIDO",
               "id":3,
               "status":"ACTIVE",
               "sort_order":4,
               "user_id":3,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"TIM PROXY 2",
            "SSH":"",
            "server_hostname":"104.18.29.182",
            "description":"TIM SALDO VALIDO",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/Z9xX94V.png",
            "user_id":12,
            "password":"",
            "udp_port":"7300",
            "category_id":"3",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"CONNECT / HTTP/1.9[crlf]host: c6bank.com.br[crlf][crlf][split][crlf]OPTIONS- // HTTP/1.9[crlf]host: br2.betao.xyzz[crlf]Expect: 200-continue[crlf]Proxy-Connection: Keep-Alive[crlf]Keep-Alive: timeout=5, max=1000[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf]Sec WebSocketExtensions: superspeed[crlf]Last-Modified: Fri, 17 March 2022 04:32:39 GMT[crlf]Server: Qnax[crlf]User-Agent: Mozilla/5.0 (Linux; Android 4.4.2); Nexus 5 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Mobile Safari/537.36 OPR/20.0.1396.72047[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_direct",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"104.18.29.182",
            "sort_order":2,
            "id":12,
            "proxy_port":80,
            "category":{
               "name":"TIM SALDO VALIDO",
               "id":3,
               "status":"ACTIVE",
               "sort_order":4,
               "user_id":3,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"TIM PROXY 3",
            "config_v2ray":"",
            "server_hostname":"104.16.51.111",
            "description":"",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/Z9xX94V.png",
            "user_id":13,
            "password":"",
            "udp_port":"7300",
            "category_id":"3",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"CONNECT / HTTP/1.9[crlf]host: c6bank.com.br[crlf][crlf][split][crlf]OPTIONS- // HTTP/1.9[crlf]host: br2.betao.xyzz[crlf]Expect: 200-continue[crlf]Proxy-Connection: Keep-Alive[crlf]Keep-Alive: timeout=5, max=1000[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf]Sec WebSocketExtensions: superspeed[crlf]Last-Modified: Fri, 17 March 2022 04:32:39 GMT[crlf]Server: Qnax[crlf]User-Agent: Mozilla/5.0 (Linux; Android 4.4.2); Nexus 5 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Mobile Safari/537.36 OPR/20.0.1396.72047[crlf][crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_direct",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"104.16.51.111",
            "sort_order":3,
            "id":13,
            "proxy_port":80,
            "category":{
               "name":"TIM SALDO VALIDO",
               "id":3,
               "status":"ACTIVE",
               "sort_order":4,
               "user_id":3,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"TIM EXPIRADO 1",
            "config_v2ray":"",
            "server_hostname":"br2.betao.xyzz",
            "description":"",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/Wn26Zn5.png",
            "user_id":14,
            "password":"",
            "udp_port":"7300",
            "category_id":"4",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"HTTP/ [crlf][crlf]Host: pre.megassh.xyzz[protocol][crlf]|[crlf]",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_proxy",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"pre.megassh.xyz",
            "sort_order":1,
            "id":14,
            "proxy_port":80,
            "category":{
               "name":"TIM EXPIRADO",
               "id":4,
               "status":"ACTIVE",
               "sort_order":5,
               "user_id":4,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         },
         {
            "name":"TIM EXPIRADO 2",
            "config_v2ray":"",
            "server_hostname":"pre.megassh.xyz",
            "description":"",
            "username":"",
            "server_port":80,
            "icon_image":"https://i.imgur.com/Wn26Zn5.png",
            "user_id":15,
            "password":"",
            "udp_port":"7300",
            "category_id":"4",
            "v2ray_uuid":"",
            "primary_dns_server":"8.8.8.8",
            "payload":"http/ \\n\\n/",
            "status":"ACTIVE",
            "secondary_dns_server":"8.8.4.4",
            "sni":"",
            "config_mode":"ssh_proxy",
            "url_check_user":"https://interflashplussshpro.alphi.media/checkuser/glmod.php?user=",
            "config_openvpn":"",
            "proxy_hostname":"pre.megassh.shop",
            "sort_order":2,
            "id":15,
            "proxy_port":80,
            "category":{
               "name":"TIM EXPIRADO",
               "id":4,
               "status":"ACTIVE",
               "sort_order":5,
               "user_id":4,
               "slug":"e5f3da23-dd2d-4871-9a03-59e315080e7c",
               "description":""
            }
         }
      ]
   }
}
